### PR TITLE
handle version-objects

### PR DESCRIPTION
**Pull request by mohawk2**
This is needed in order for https://github.com/jjn1056/DBIx-Class-Migration/issues/113 to be fully fixed (although DBICM has been patched and is about to be released).

### CODE REVIEW

**Comment by mohawk2** [comment]
...well, the patch is on a branch until DBICDH is merged and released!

**Comment by mohawk2** [comment]
@frioux ?

**Comment by frioux** [comment]
I'm pretty busy with other things right now; you want comaint?

**Comment by mohawk2** [comment]
Ok. ETJ on PAUSE, and could you add me on the repo?

**Comment by frioux** [comment]
I added both you and @wesQ3 as contributors for this repo and comaint for releasing to CPAN.  Thanks and good luck!

**Comment by mohawk2** [comment]
@frioux Great, thanks!

@wesQ3 My intent is to merge/release this soon (day or two). Please shout up if you object.

I'll also be looking in more detail at the other open PR and doing a scan of open issues, with a view to fixing them and releasing either dev or stable according to my assessment of risk.

**Comment by wesQ3** [comment]
@mohawk2 This looks good to me. Thanks for your work :+1:

**Comment by mohawk2** [comment]
Released as 0.002223

**Pull request merged**
