### PR TITLE
Revert conversion to Moo

### PR DESCRIPTION
**Pull request by mmcclimon**
See #69. This branch reverts everything to v0.002224 (before the conversion to Moo), and includes one fix (861d854) for the Pg splitting problem I was having there.

Pinging @mohawk2 since we've been talking about it, but I am happy to merge and release this.

### CODE REVIEW

**Comment by mmcclimon** [comment]
I added a commit that has your Moo vs. Moose test in it, which I forgot the first time around!

**Comment by mohawk2** [comment]
I am very strongly opposed to this.

Quite apart from anything else, there is at least one subclasser who has already switched to a Moo class and would need to change their code again.

Since you have successfully changed your code, what do you think you are achieving by this?

**Comment by frioux** [comment]
@mohawk2 one person has changed; how many people have not yet upgraded but will be broken by a change in documented behavior?

**Comment by frioux** [comment]
If you want a faster fork of DBICDH that is only Moo I would say that's just fine, but breaking backcompat and then claiming that you have to maintain backcompat after one person upgraded is absurd.

**Comment by mmcclimon** [comment]
> Since you have successfully changed your code...

I only half-successfully changed my code, and it required more work than a mechanical translation (which, for the record, I _also_ would have been opposed to). Doing the translation also changed the _behavior_ of my existing code.

>  ...what do you think you are achieving by this?

Backward compatibility, which I've said numerous times. Our existing library code worked through version 0.002223, and is broken in _every version_ from 0.002224 onward. Moreover, the breaking change was and is not documented, and there is not even (IMO) a good reason for the breakage. That's user-hostile behavior, and also goes against the norms of CPAN and of perl in general, which has a very strong commitment to backcompat (which is broken, effectively, _only_ in the case of security problems).

As @frioux says, it seems ridiculous to me that you say we must maintain backcompat for a change made in the last month, affecting (as far as you have said) a single user, while at the same time, ignoring your backwards-incompatible and undocumented changes for the previous _years_ of releases, many of which will be broken unexpectedly and without warning.

**Comment by mmcclimon** [comment]
I had sort of forgotten about this in the haze of some other work, but I am now coming back to this. I propose to merge and release this later this week.

**Comment by frioux** [comment]
👍

--

**Pull request merged**
